spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/bruh'
    username: 'usr'
    password: 'pw'
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  show-actuator: true
